### PR TITLE
Csv uploader

### PR DESCRIPTION
**Pull request by JYL123**

### CODE REVIEW

**Comment by JYL123** [comment]
input csv string format: no space should be needed in between any two characters, if there is any space included, the space will be treated as if it is part of the text. The output of the csv string is an array which is Json format.

**Comment by thchia** [comment]
What is the format of the children properties in the csv? E.g. `references.MyReference.referenceValue` ?

**Comment by JYL123** [comment]
The values of the properties will be converted into strings, except when the strings consist of numbers, which will be converted into integers, and when the strings are boolean values will be converted into boolean values.

**Comment by thchia** [comment]
What I mean is if I want to use this, what headings do I need in my Excel spreadsheet so that it works.

**Comment by JYL123** [comment]
It does not have any specification or limitations on headings. Headings can be specified partially, e.g. references.MyReference.referenceValue=testValue, references.MyReference.active=false, but in the outcome, all properties of the class (e.g. all properties of the Reference class) will be in the Json array with "undefined"/default value "TEMP" assigned to the properties that are not specified in the csv string.

**Comment by thchia** [comment]
Ok so the format of the children headings is:

`childType.childName.childProperty`.

How about for Links? Is it

`links.MyLink.0.linkedTransactionId` ? Or
`links.MyLink[0].linkedTransactionId`

Because Links can have several children in an Array.

**Comment by JYL123** [comment]
For Link, to get the value, links.MyLink[0].linkedTransactionId is the one.

**Comment by thchia** [comment]
I think you may need to look at the test assertions... There is a failing test, although the output looks more or less correct.

**Comment by JYL123** [comment]
Oops. Sorry for keeping the request open. I changed the test cases yesterday for more rigorous testing. I will temporarily close the request until I have done the testing.

**Pull request closed without merging**
