### PR TITLE
Export Classes and API methods separately

### PR DESCRIPTION
**Pull request by thchia**
### Modules
This PR defines the following named exports:
* AssetManagers
* Assets
* Books
* Parties

Each of these modules defines a `Class` and an `api` export. `Class` contains all the relevant classes for that module, while `api` contains the relevant API methods for that module.

The available `api` methods available for each module are documented below:
* __AssetManagers.api__
  * .retrieve()
  * .insert()
  * .amend()
  * .deactivate()
  * .reactivate()
* __Assets.api__
  * .retrieve()
  * .insert()
  * .amend()
  * .partialAmend()
  * .deactivate()
  * .reactivate()
* __Books.api__
  * .retrieve()
  * .insert()
  * .retire()
  * .reactivate()
* __Parties.api__
  * .retrieve()
  * .insert()
  * .amend()
  * .partialAmend()
  * .deactivate()
  * .reactivate()

### Examples
* Instantiate an Equity class
```javascript
import { Assets } from 'amaas-core-sdk-js'

let equity = new Assets.Class.Equity(params)
```

* Retrieve an Equity from the database (with promise)
```javascript
import { Assets } from 'amaas-core-sdk-js'

const params = {
  AMId: 1, // Asset Manager ID
  resourceId: xyz, // Asset ID
  token: abc // Authorization token
}

Assets.api.retrieve(params)
  .then(res => {
    // Resolves with an Asset instance or array of Assets
  })
  .catch(err => {
    // Catch reject
  })
```
* Retrieve an Equity from the database (with callback)
```javascript
import { Assets } from 'amaas-core-sdk-js'

const params = {
  AMId: 1, // Asset Manager ID
  resourceId: xyz, // Asset ID
  token: abc // Authorization token
}

Assets.api.retrieve(params, (err, res) => {
  if (res) {
    console.log(res) // an Asset instance or array of Assets
  }
})
```

### CODE REVIEW

**Comment by steverandy** [comment]
I haven't looked at the new code, but I have one quick comment. 

With the api namespace not being the top level, if we want to configure for example the env (staging, prod, etc), how will the code look like?

**Comment by thchia** [comment]
Not sure yet. But what do you mean about it not being top level? Does that affect the config?

**Comment by steverandy** [comment]
Top level api namespace will be something like:
```javascript
import {api} from 'amaas-core-sdk-js';
api.config({key: value});
api.Books.retrieve();
```

This way we can use api as a shared object for storing an api config for example.

---


I have reviewed the new code. Here some suggestions based on the current design:
```javascript
import {assets} from 'amaas-core-sdk-js';
let equity = new assets.Equity(params);
assets.api.retrieve(params);
```

- `assets` should be lowercase because it's not a class.
- I think there is no need to add additonal `Class` namespace to wrap the child classes.

**Comment by thchia** [comment]
If api was a top-level namespace, would we nest the classes under this, or have them separate (I don't know if we really need a config for the classes..?)

```javascript
import { api } from 'amaas-core-sdk-js'

api.Assets.retrieve()
let equity = new api.Assets.Equity(params)
```

Or

```javascript
import { api, assets } from 'amaas-core-sdk-js'

api.Assets.retrieve()
let equity = new assets.Equity
```

**Comment by steverandy** [comment]
It will be the 2nd one. It will give a clear separation between api and the classes.

**Comment by thchia** [comment]
Ok. If you are happy with this I will implement it. Before I do that do you have any alternative ideas (even if they are not totally in keeping with the current design)?

**Comment by steverandy** [comment]
Cool. Let's discuss later separately.
We can merge this PR first.

**Pull request merged**
